spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    open-in-view: false
    generate-ddl: true
    format-sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
